# the name of the workflow
name: demo
# the trigger event
on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# jobs are the tasks run in the workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-20.04
    container: 
      image: ros:noetic-ros-base
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: install curl
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install curl
    - name: SonarCloud Scan for C and C++
      uses: SonarSource/sonarcloud-github-c-cpp@v1.3
    - name: Run build-wrapper
      run: |
        # build-preparation steps
        source /opt/ros/noetic/setup.bash
        cd ./hiwi_ws
        build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} catkin_make
    - name: Run sonar-scanner
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: sonar-scanner --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}" #Consult https://docs.sonarcloud.io/advanced-setup/ci-based-analysis/sonarscanner-cli/ for more information and options
  # A job name 
  test_ros_node:
    # env settings, support fot Ubuntu/Windows/macOS
    runs-on: ubuntu-20.04
    # run the code on a docker container
    container: 
      image: ros:noetic-ros-base
    # step is the smallest executable unit
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
        
      - name: build the workspace
        shell: bash
        # "|" stands for multiline commands
        run: |
          source /opt/ros/noetic/setup.bash
          cd ./hiwi_ws
          catkin_make
          source devel/setup.bash
          rostest order_publisher order_publisher.test

          
