# the name of the workflow
name: demo
# the trigger event
on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# jobs are the tasks run in the workflow
jobs:
  # A job name 
  test_ros_node:
    # env settings, support fot Ubuntu/Windows/macOS。
    runs-on: ubuntu-20.04
    # run the code on a docker container
    container: 
      image: ros:noetic-ros-base
    # step is the smallest executable unit
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
        
      - name: build the workspace
        shell: bash
        # "|" stands for multiline commands
        run: |
          source /opt/ros/noetic/setup.bash
          cd ./hiwi_ws
          catkin_make
          source devel/setup.bash
          rostest order_publisher order_publisher.test

          
