# the name of the workflow
name: demo

# the trigger event
on:
  # triggered after push
  push:
    branches: 
    - master
  # trggered after pull request
  pull_request:
    branches:
    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# jobs are the tasks run in the workflow
jobs:
  # A job 
  test_ros_node:
    # in which env the job runs, support fot Ubuntu/Windows/macOS。
    runs-on: ubuntu-20.04

    # step is the smallest executable unit
    steps:
      - name: use docker image
        uses: docker://ros:noetic-ros-base

      - uses: actions/checkout@v3
      
      # build the workspace
      - name: build the workspace
        shell: bash
        run: catkin_make
        working-directory: ./hiwi_ws
          
          #source devel/setup.bash
          #rostest order_publisher order_publisher.test

          
